// Type declarations for @itslil/lil2-mdast-util-to-hast. Generated by lilscript-work/lil2/release/types.mjs.
/**
 * hast as positional columns: the transformer's own arrays, indexed by node id; `root` is the root's id.
 *
 * A node's kind is `kind[node]`, one of the `H_*` constants (`/constants`); an element's tag
 * name is `tagNames[tag[node]]` and text, comment and raw nodes keep their text in `value`. Children run from
 * `firstChild[node]` along `nextSibling`; -1 ends the list and means "none" in every link column. An element's
 * properties run from `propHead[node]` along `propNext`: each has a name (`propNames[propName[p]]`), a kind
 * (`P_*`: string, number, boolean, list, keyword or float) and its value in `propString` (string and list
 * values; a list is space separated) or `propNumber` (numbers, booleans as 0/1, and `P_KEYWORD` ids into
 * `keywordNames`). Positions are offsets into the source; `lineStarts` turns an offset into a line and column.
 */
export type HastColumns = readonly [
  root: number,
  kind: readonly number[],
  parent: readonly number[],
  firstChild: readonly number[],
  nextSibling: readonly number[],
  tag: readonly number[],
  value: readonly string[],
  startOffset: readonly number[],
  endOffset: readonly number[],
  flags: readonly number[],
  meta: readonly string[],
  propHead: readonly number[],
  propName: readonly number[],
  propKind: readonly number[],
  propString: readonly string[],
  propNumber: readonly number[],
  propNext: readonly number[],
  lineStarts: readonly number[],
  tagNames: readonly string[],
]

/** Property names by id (`propName` values index it). */
export declare const propNames: readonly string[]
/** Keyword values by id (a `P_KEYWORD` property's `propNumber` indexes it). */
export declare const keywordNames: readonly string[]

/**
 * Markdown to hast columns: mdast-util-from-markdown, then mdast-util-to-hast 13 (remark-rehype's defaults).
 * @param allowDangerousHtml Keep raw HTML as `raw` nodes (to-hast's `allowDangerousHtml`); default false.
 */
export declare function markdownToHast(value: string, allowDangerousHtml?: boolean): HastColumns
